version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - wind-turbine-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlflow.db:/mlflow/mlflow.db
    command: >
      mlflow server 
      --backend-store-uri sqlite:///mlflow/mlflow.db 
      --default-artifact-root /mlflow/mlruns 
      --host 0.0.0.0 
      --port 5000
    restart: always
    networks:
      - wind-turbine-network

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: wind-turbine-api
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - mlflow
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    restart: always
    networks:
      - wind-turbine-network

networks:
  wind-turbine-network:
    driver: bridge

volumes:
  mongodb_data: