channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=25.1.1
- pip:
  - mlflow==3.1.0
  - cloudpickle==3.0.0
  - lz4==4.3.3
  - numpy==1.26.4
  - psutil==5.9.8
  - scikit-learn==1.4.1.post1
  - scipy==1.12.0
name: mlflow-env
