name: Wind Turbine MLflow Pipeline CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Weekly run on Sunday at midnight

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Lint code
        run: |
          pip install flake8
          flake8 src tests

      - name: Run tests
        run: |
          pytest --cov=src --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml

  train:
    needs: test
    runs-on: windows-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
      mlflow:
        image: python:3.10
        ports:
          - 5000:5000
        options: >
          --health-cmd "curl --fail http://localhost:5000 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - ${{ github.workspace }}/mlruns:/mlruns
        entrypoint: ["bash", "-c"]
        command: "pip install mlflow && mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns --host 0.0.0.0 --port 5000"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load data to MongoDB
        run: python src/data/load_data.py

      - name: Train models
        run: python src/models/train.py

      - name: Evaluate models
        run: python src/models/evaluate.py

      - name: Archive model artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: |
            models/
            outputs/
            mlruns/

  deploy:
    needs: train
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download model artifacts
        uses: actions/download-artifact@v3
        with:
          name: model-artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.yogeshkore31 }}
          password: ${{ secrets.dckr_pat_63U_KUBWvEp-ZRZwLZ21zINt7jE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.yogeshkore31 }}/wind-turbine-mlflow:latest